### ISSUE TITLE
Discussion: Zicond and RVA profiles

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-zicond#10]
It does not look like Zicond is intended to be part of any future profile (at least it is not mentionned in https://github.com/riscv/riscv-profiles/blob/main/rva23-profile.adoc). Is the extension intended to be integrated into a profile at some point ?

**Comment by ptomsich** [comment]
@kasanovic Krste, could you comment on this?

**Comment by kasanovic** [comment]
Zicond is too new to have been included in that RVA23 draft.  Assuming it is ratified before RVA23, it should at least be optional.  It is the type of instruction that will eventually be mandatory in RVA, though there has been little discussion so far about whether that would happen in RVA23 or later.

**Comment by ptomsich** [comment]
We will add comment to this effect to the final specification version.

**Comment by nibrunieAtSi5** [comment]
Thank you @kasanovic and @ptomsich .
