### ISSUE TITLE
Opcode overlap between czero.eqz and cmov

### ISSUE THREAD

**Issue by deepsrc** [riscv/riscv-zicond#12]
We seem to be having an opcode overlap between cmov (Zbt) and czero.eqz (Zicond)

The opcode format for czero.eqz is given below -

`00001 11 | rs2 | rs1 |  101 | rd | 0110011`

Similarly the opcode format for cmov is -

`rs3 | 11 | rs2 | rs1 | 101 | rd | 0110011`

Some of our tests which check for illegal traps with czero.eqz in implementations not supporting Zicond are failing when Zbt is supported.

The spec also does not say anything about these extensions/instructions not being compatible with each other.

Can you please look into this and provide some clarification?

**Comment by ptomsich** [comment]
Zbt never made it to the freeze-milestone (only an old draft proposal exists, which should be considered abandoned, and the cited opcodes have never undergone architecture-review).  In contrast, Zicond has been ratified.

**Comment by ptomsich** [comment]
> We seem to be having an opcode overlap between cmov (Zbt) and czero.eqz (Zicond)

Given that Zbt is neither contained in the public-review version of the Zb[abcs] extensions nor in the final, ratified Zb[abcs] specification: where is Zbt published (so we can track this down and add appropriate warnings there)?

**Comment by aswaterman** [comment]
Thanks for raising the issue, @deepsrc.  Should be resolved by https://github.com/riscv-software-src/riscv-isa-sim/pull/1384.
