### ISSUE TITLE
Memory Model For rs2

### ISSUE THREAD

**Issue by mehnadnerd** [riscv/riscv-zicond#5]
The current proposal states `This instruction behaves as if there is a conditional branch dependent on rs2...`, and mentions the syntactic dependency on `rs1` is only preserved if the condition is met. This would seem to imply that there is a control dependency from `rs2` to `rd`, but the text does not specify this.

**Comment by ptomsich** [comment]
@aswaterman Could you respond to this?

/assign @aswaterman

**Comment by aswaterman** [comment]
The stated equivalence to the branch-based sequence should answer this question.

**Comment by mehnadnerd** [comment]
I will do so--the additional thing I wanted to imply was that this is similar to the dependency on vl for vector instructions, where it will not apply additional ordering on future non-dependent stores. I will copy the wording from the vector specification.

**Comment by mehnadnerd** [comment]
https://github.com/riscv/riscv-zicond/pull/6

**Comment by ptomsich** [comment]
Thinking some more about this, I wonder if there is a control dependency (or it is only suggested by the equivalence of a branching structure).

Considering that these are unconditional arithmetic instructions, their true equivalence is either a lookup (as in the SAIL model) or the following arithmetic:
```
  czero.eqz rd, rs1, rs2 :=
     snez rmask, rs2
     neg rmask, rmask
     ori rd, rs1, rmask
```

Unless the slt*-family of instructions also has a control dependency, we should not claim one for czero.

**Comment by mehnadnerd** [comment]
There should be a control dependency, as opposed to a data dependency, to match the branch. If we wanted to match the slt family, we could make it DVT-invariant on _rs2_ (and always propagate the syntactic dependency on _rs1_) but that was explicitly decided against.

The term "control dependency" for operations like this, where there is an output register and no change in control flow, is currently underdefined, I have been talking with Andrew about it in the context of the V extension. The intent is that it will follow like other syntactic dependencies, but unlike address or data dependencies, will only be enforced to stores.

Since I copied the wording from the V extension, I don't think the lack of a formal definition of "control dependency" should block this extension, it can share the same formalisation.

**Comment by ptomsich** [comment]
> There should be a control dependency, as opposed to a data dependency, to match the branch. If we wanted to match the slt family, we could make it DVT-invariant on _rs2_ (and always propagate the syntactic dependency on _rs1_) but that was explicitly decided against.

As far as I understand, the slt-family is also only DVT-invariant if the Zkt extension is present... but DVT should not affect the determination of whether there is a "control dependency". 

> The term "control dependency" for operations like this, where there is an output register and no change in control flow, is currently underdefined, I have been talking with Andrew about it in the context of the V extension. The intent is that it will follow like other syntactic dependencies, but unlike address or data dependencies, will only be enforced to stores.

"Control dependency" (at least in my reading) always implies that the "observable next program-counter" depends on the value.  If an instruction unconditionally executes and advances to the same "next program-counter", we can only have a "data dependency".  To make things more involved: the data-dependency may then feed into a control-dependency of a dependent branch — but that should be covered by the model for the dependent branch then, right?

I would suggest that we refine the wording/definition of "control dependency": the design of Zicond intentionally made its instructions unconditional (and the various discussions around the topic of control dependencies have arisen only from whether prediction of the output-value — and consequently the prediction of successive branches dependent on its output value — would be appropriate).

The situation seems to be common with other instructions, where data-prediction on the output could be used to predict a conditional branch (e.g. andi rd, rs1, #imm -> beqz/bnez).

I may be barking up an entirely wrong tree, though…

> Since I copied the wording from the V extension, I don't think the lack of a formal definition of "control dependency" should block this extension, it can share the same formalisation.

**Comment by mehnadnerd** [comment]
The V extension has this sentence, which raises similar issues:
"Instructions affected by the vector length register vl have a control dependency on vl, rather than a data dependency. Similarly, masked vector instructions have a control dependency on the source mask register, rather than a data dependency."
The next program-counter does not depend on vl in this case, so the standard definition of "control dependency" cannot be used. I am working on creating a modification that is able to handle this case, I am tentatively calling it a "reconvergent control dependency" or "rcontrol dependency". It will need to be another type of syntactic dependency that is passed through operations, and we will need a PPO rule 11b that states ": b is a store, and b has a syntactic reconvergent control dependency on a". I think a similar expanded definition of a "control dependency" would be appropriate here. There are definitely some holes and work here, but I wanted to use the fact that we can copy from the V extension to kick that particular can down the road.

What I was trying to say with the DVT statements is that these conditional select statements are more like branches than bit manipulation. Not guaranteeing DVT was an example of how it was more similar to a branch, as is only propagating the syntactic dependency on rs1 if the condition passes.

**Comment by kdockser** [comment]
As [mehnadnerd](https://github.com/mehnadnerd) points out, these Zicond instructions are different from other instructions in that one of the operands (rs1) is not evaluated if the condition is true. For hardware, this means that the instruction can complete when the condition is true even if rs1 is not ready.
Since the SAIL model is a Formal model, and not just a behavioral model, it's code should be changed to reflect the branch-like behavior of these instructions. This control dependency also needs to be indicated in any supplemental files for use in memory concurrency testing (e.g., RMEM and isla-axiomatic).

**Comment by ptomsich** [comment]
> As [mehnadnerd](https://github.com/mehnadnerd) points out, these Zicond instructions are different from other instructions in that one of the operands (rs1) is not evaluated if the condition is true. For hardware, this means that the instruction can complete when the condition is true even if rs1 is not ready. Since the SAIL model is a Formal model, and not just a behavioral model, it's code should be changed to reflect the branch-like behavior of these instructions. This control dependency also needs to be indicated in any supplemental files for use in memory concurrency testing (e.g., RMEM and isla-axiomatic).

SAIL provides a formal model of the architecture, but you describe micro-architectural aspects in waiting (or not waiting) for the readiness of operands.  That would require some sort of pipeline model (or at least readiness-constraints) to be expressed in the SAIL model.

As of today, the SAIL model can only model a branching behavior by updating the program-counter (something that is not an option here).  SAIL always requires all architectural arguments to be ready (as they are parameters to the function call to EXECUTE).

**Comment by kdockser** [comment]
The conditional dependency is an architectural feature. The formal model must represent this as it is the golden specification and may be used for Formal verification with an implementation as well as for concurrency testing with the aid of other tools.

That said, it seems like the SAIL language is not able to handle such a conditional dependency at this time. It seems like this is a gap that should be addressed.

**Comment by mehnadnerd** [comment]
I agree with Ken's point that we need to model this properly in SAIL in order to properly match the semantics of this instruction. The current SAIL will not match the conditional dependency on rs1, which will be visible in the memory model.
For czero.eqz, would 
`let condition = X(rs2);
  result : xlenbits = if (condition == zeros()) then zeros()
                                                else X(rs1);
  X(rd) = result;`
  work/be valid SAIL? We need to only read rs1 if the condition is met.

**Comment by mehnadnerd** [comment]
@ptomsich were you going to accept my MR and close this issue? I thought that was what you were going to do based on our discussion.

**Comment by ptomsich** [comment]
Merged.

**Comment by aswaterman** [comment]
@mehnadnerd what’s next as far as defining these reconvergent control dependencies?

**Comment by mehnadnerd** [comment]
I haven't gotten a positive response from the memory model experts, I will try again.
